### ISSUE TITLE
ERROR: Unknown resource Type : OOShift::LoadBalancer

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#112]
I'm confused if this means my Neutron doesn't support LBaaS (which it seems to as all the commands are present on the CLI) or rather there is some basic configuration error.  I haven't selected LB either way - I'm going with the defaults with master_count=3

**Comment by jprovaznik** [comment]
It might be you miss following lines in your env file:
https://github.com/redhat-openstack/openshift-on-openstack/blob/master/env_aop.yaml#L19-L20

**Comment by juddmaltin-dell** [comment]
Yes, thank you.  Indeed, I missed those lines.  The heat templates started up when I added them. Interestingly, my lbaas-agents weren't running on any of my controllers, but heat accepted them.  Got the lbaas-agents started up, but the install is hanging on the openshift-infra install.  I'll save that for another issue.
