### ISSUE TITLE
Not seeing why stack-create doesn't continue

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#115]
I added the pools I needed by adding parameters to the heat templates and code (patch forthcoming) and the os-collect-config package installs and runs OK.

But stack-create is still hanging on the infra node install. I'm not seeing why in the above cloud-init.log  I'm on RHEL7.2  Should ansible be kicked off before cloud-init is done?

https://gist.github.com/866346d7f5359b43e167b25b89628a8c

**Comment by jprovaznik** [comment]
cloud-init finished successfully on infra node. So setup should proceed with creating master node. If not, something unusual happened. Could you please attach output of "heat event-list -n 2 stackname" and "heat resource-list -n 2 stackname"?

**Comment by juddmaltin-dell** [comment]
It was the heat publicURL issue.  Closed.
