### ISSUE TITLE
How to change metadata_url?

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#116]
The heat-api-cfn metadata_url is not accessible from my vm.  Cloud-init migth be suffering from this.
How do I change the metadata_url?

I'll change it to something on the public API network, that already has haproxy listening on those ports, forwarding as usual

**Comment by lebauce** [comment]
The `metadata_url` in the VM comes from the /etc/heat/heat.conf configuration file on the Openstack controller nodes. IIRC, you need to modify the values `heat_metadata_server_url` and
`heat_waitcondition_server_url` and restart the Heat services.

**Comment by juddmaltin-dell** [comment]
Wouldn't it rather be taken from the service endpoints?   How might I get the publicURLs to be used instead?

[heat-admin@tan-controller-0 ~]$ openstack endpoint show heat
+--------------+----------------------------------------------+
| Field        | Value                                        |
+--------------+----------------------------------------------+
| adminurl     | http://192.168.140.70:8004/v1/%(tenant_id)s  |
| enabled      | True                                         |
| id           | e7e1d48dcdeb4b17a363f4e2a348771a             |
| internalurl  | http://192.168.140.70:8004/v1/%(tenant_id)s  |
| publicurl    | http://192.168.190.125:8004/v1/%(tenant_id)s |
| region       | regionOne                                    |
| service_id   | 9fded7b9ef5c416e9cce44e0c1cfcedd             |
| service_name | heat                                         |
| service_type | orchestration                                |
+--------------+----------------------------------------------+

going to try out your suggestion first, though.  Thanks!

**Comment by juddmaltin-dell** [comment]
Wouldn't it rather be taken from the service endpoints?   How might I get the publicURLs to be used instead?

[heat-admin@tan-controller-0 ~]$ openstack endpoint show heat
+--------------+----------------------------------------------+
| Field        | Value                                        |
+--------------+----------------------------------------------+
| adminurl     | http://192.168.140.70:8004/v1/%(tenant_id)s  |
| enabled      | True                                         |
| id           | e7e1d48dcdeb4b17a363f4e2a348771a             |
| internalurl  | http://192.168.140.70:8004/v1/%(tenant_id)s  |
| publicurl    | http://192.168.190.125:8004/v1/%(tenant_id)s |
| region       | regionOne                                    |
| service_id   | 9fded7b9ef5c416e9cce44e0c1cfcedd             |
| service_name | heat                                         |
| service_type | orchestration                                |
+--------------+----------------------------------------------+

I tried out your suggestion, but it didn't work. :(

**Comment by jprovaznik** [comment]
Enable using public endpoint url has been added to heat quite recently  - https://github.com/openstack/heat/blob/master/heat/engine/clients/os/heat_plugin.py#L83, so with a _new_ version you can use public url by setting OS_ENDPOINT_TYPE=publicURL when using heat client. Otherwise you have to change urls as @lebauce said.

If changing them in config file (and restarting heat services) didn't help, I wonder if the problem is really in wrng url? Maybe iptables?

**Comment by juddmaltin-dell** [comment]
I was wrong - changing /etc/heat/heat.cfg was correct.  Thank you.
