### ISSUE TITLE
why not setup OpenShift for OpenStack?

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#134]
https://docs.openshift.com/enterprise/3.1/install_config/configuring_openstack.html

We have all the data.  Do the ansible playbooks not support this?

**Comment by lebauce** [comment]
This is supported by those Heat templates.

You need to pass the `os_auth_url`, `os_username`, `os_password` and `os_tenant_name` parameters to the stack.
The templates also allow you to deploy a registry that uses a Cinder volume for persistence by adding the `deploy_registry` parameter to the parameters listed above.

**Comment by juddmaltin-dell** [comment]
OSE 3.1 on OSP 8 on RHEL 7.2

I set them

```
[osp_admin@director openshift-on-openstack]$ grep os_ openshift_parameters.yaml
  os_auth_url: http://192.168.190.125:5000/v2.0
  os_username: admin
  os_password: pZ4CGyJU4XDbEuMVT7qMKdP6b
  os_tenant_name: admin
```

But I don't see them:

```
[root@delloss-openshift-master-0 origin]# grep -ri openstack /etc/origin/
[root@delloss-openshift-master-0 origin]# echo $?
1
```

and

```
[root@delloss-openshift-master-0 origin]# grep -ri auth-url /etc/
[root@delloss-openshift-master-0 origin]#
```

Do I need to restart OpenShift for it to write out configs it might have gotten via API?

Thanks!

ed:

Infra host doesn't know about them:

```
[root@delloss-infra ~]# grep -i os_auth_url /var/log/ansible.29239
[root@delloss-infra ~]# grep -i os_auth_url /var/log/cloud-init.log
[root@delloss-infra ~]#
```

Master cloud-init and messages doesn't seem to know:

```
[root@delloss-openshift-master-0 origin]# grep -i os_auth_url /var/log/cloud-init.log
[root@delloss-openshift-master-0 origin]# grep -i os_auth_url /var/log/messages
[root@delloss-openshift-master-0 origin]#
```

**Comment by lebauce** [comment]
You need OSE 3.2 for this to be usable. We just merged this PR https://github.com/redhat-openstack/openshift-on-openstack/pull/135 that switches to 3.2. Could you please give it a try ?

**Comment by juddmaltin-dell** [comment]
Worked great with 3.2.  Thanks!

**Comment by juddmaltin-dell** [comment]
Worked great with 3.2.  Thanks!
