### ISSUE TITLE
could not install EPEL release 7-6

### ISSUE THREAD

**Issue by alessiodini** [redhat-openstack/openshift-on-openstack#158]
Hello all,
launching a new stack from this project I got this error:

| my-openshift                                                   | d6d97dda-af0d-49cd-a269-7aba87d3b61c | Resource CREATE failed: WaitConditionFailure: resources.infra_host.resources.wait_condition: could not install EPEL release 7-6              | CREATE_FAILED      | 2016-06-22T10:24:11Z | my-openshift    

Looking fragments/infra-boot.sh there are those lines:
EPEL_RELEASE_VERSION=7-6
EPEL_REPO_URL=http://dl.fedoraproject.org/pub/epel/7/x86_64

If u check on http://dl.fedoraproject.org/pub/epel/7/x86_64/e/ there is only 7-7 version , so the line posted above should be changed in:
EPEL_RELEASE_VERSION=7-7

Regards
Alessio Dini

**Comment by juddmaltin-dell** [comment]
I'm seeing this, too.

**Comment by juddmaltin-dell** [comment]
I've fixed this so we will not see it again.  #161 fall back to epel-release-latest-7 if hardcoded 7-minor unavailable

**Comment by jprovaznik** [comment]
@juddmaltin-dell thanks for fixing this.
