### ISSUE TITLE
SSH Error: ssh: connect to host my-openshift-origin-node-v00ba4cf.example.com port 22: Connection timed out

### ISSUE THREAD

**Issue by alessiodini** [redhat-openstack/openshift-on-openstack#162]
Hello all,
I have this issue:
during the deploy of this project , Infra node maps on /etc/hosts the wrong ip class.
Infra host has one interface with 192.168.0.0/24 network but the /etc/hosts has:

[root@my-openshift-infra centos]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.0.0.2 my-openshift-origin-master-0.example.com my-openshift-origin-master-0 #openshift
10.0.0.3 my-openshift-origin-master-1.example.com my-openshift-origin-master-1 #openshift
10.0.0.4 my-openshift-origin-node-44b91tzk.example.com my-openshift-origin-node-44b91tzk #openshift
10.0.0.5 my-openshift-origin-node-v00ba4cf.example.com my-openshift-origin-node-v00ba4cf #openshift

During the Ansible playbook execution I have a lot of error due to ssh connections timed out:

(...)
fatal: [my-openshift-origin-master-1.example.com] => SSH Error: ssh: connect to host my-openshift-origin-master-1.example.com port 22: Connection timed out
    while connecting to 10.0.0.3:22
(...)
=> SSH Error: ssh: connect to host my-openshift-origin-node-v00ba4cf.example.com port 22: Connection timed out while connecting to 10.0.0.5:22

I actually can bypass this updating manually the /etc/hosts file during the HEAT deploy , but this should be fixed.

Regards
Alessio Dini

**Comment by jprovaznik** [comment]
Hi,
it might be that "{get_attr: [host, first_address]}" which is used for getting the IP may is random (doesn't reflect the ordering in host's "networks" list): https://github.com/redhat-openstack/openshift-on-openstack/blob/master/master.yaml#L411

We should refer the fixed_network ip address by some other way.

**Comment by jprovaznik** [comment]
@adini83 I couldn't reproduce this but I hope the patch above fixes the issue.
