### ISSUE TITLE
Cannot reach pod services from master

### ISSUE THREAD

**Issue by alessiodini** [redhat-openstack/openshift-on-openstack#166]
Hello all,
I deployed a simple hello-openshift but I'm not able to contact it from master.
I remember this action was possible , downloading this project code some week ago. ( I still have these sources saved )
Now the scenario is:

[root@my-openshift-origin-master-0 origin]# oc describe pod hello-openshift | grep -i ip
IP:             10.1.1.2

[root@my-openshift-origin-master-0 origin]# curl http://10.1.1.2:8080
curl: (7) Failed connect to 10.1.1.2:8080; No route to host

[root@my-openshift-origin-master-0 origin]# ping 10.1.1.2
PING 10.1.1.2 (10.1.1.2) 56(84) bytes of data.
^C
--- 10.1.1.2 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 1999ms

Exposing the service and adding the wildcard to an external DNS server is not letting me reach the exposed service . How can I reach that service if the master first does not do it?
Sorry for my bothering questions but I need to understand !!!
Regards
Alessio Dini

**Comment by alessiodini** [comment]
Update:

I rolled-back to a previous code I saved , I made a new HEAT deploy and repeating the same steps as above now I'm able to expose and contact the service:

[root@my-openshift-origin-master-0 tmp]# oc describe pod hello-openshift | grep -i ip
IP:             10.1.1.2
[root@my-openshift-origin-master-0 tmp]# curl http://10.1.1.2:8080
Hello OpenShift!

The curl from an external client now is working.
My question is: What I'm missing with the latest code ? What's changed?
I want to run the latest code !!
Regards
Alessio Dini

**Comment by jprovaznik** [comment]
Hi @adini83 - I can confirm this issue, based on your information I guess there is a regression, my first thought is it might be this one - https://github.com/redhat-openstack/openshift-on-openstack/commit/0d32253851cca684f0fe34a2dbb79f5e2a6cf37c

I'll try with the patch reverted, if you could send diff between your old templates and new, it would help.
