### ISSUE TITLE
heat stack-create error

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#172]
Hi everyone, I use mitaka version of openstack, and installed every services that we needed it, but when I executes below command:

 heat stack-create my-openshift -t 180   -e openshift_parameters.yaml   -f openshift-on-openstack/openshift.yaml -e openshift-on-openstack/env_loadbalancer_none.yaml

I get This error:
    ERROR: Failed to validate: Failed to validate: resources[0]: The Resource Type  (OOShift::ContainerPort) could not be found.

please help me to understand what is my problem..
Thanks

**Comment by jprovaznik** [comment]
@mahsa-frj I guess it's because templates refers some custom resource types. Could you please try add following lines into your openshift_parameters.yaml file:

```
resource_registry:
    OOShift::LoadBalancer: openshift-on-openstack/loadbalancer_neutron.yaml
    OOShift::ContainerPort: openshift-on-openstack/sdn_openshift_sdn.yaml
    OOShift::IPFailover: openshift-on-openstack/ipfailover_keepalived.yaml
```

**Comment by mahsa-frj** [comment]
@jprovaznik  thanks. your solution was true.
