### ISSUE TITLE
Create TimedOut

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#180]
Hi everybody, because I don't have enough space in my local environment, I changed the openshift_parameters.yaml, and I have one master and one node, and set the docker volume size of both master and node to 10G.
and when I execute below command:

```
heat stack-create my-openshift -t 180 \
-e openshift_parameters.yaml \ 
-f openshift-on-openstack/openshift.yaml
```

after 3 hour, the Create TimedOut in infra_host section appears.
please help me to understand what is my problem.

**Comment by jprovaznik** [comment]
Hi, changing volume_size is fine. If it hangs in infra_host, most probably cloud-init didn't failed on infra node (and no notification has been sent back), could you ssh to the infra host and check /var/log/cloud-init.log if there is a hint?

**Comment by jprovaznik** [comment]
Closing this, if the problem still occurs please reopen (more information like /var/log/cloud-init.log will be needed).
