### ISSUE TITLE
ansible version is low corresponding to openshift-ansible reqired

### ISSUE THREAD

**Issue by zhangjunli177** [redhat-openstack/openshift-on-openstack#181]
In openshift-on-openstack/fragments/infra-boot.sh, ansible1.9 is installed.
In openshift-ansible/openshift-ansible.spec of master branch, ansible >= 2.1.0.0 is required.
Which cause the installation failed if use the following environment:
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  openshift_ansible_git_rev: master

**Comment by jprovaznik** [comment]
Hi @zhangjunli177 , thanks for pointing this out - yes openshift-ansible switched to ansible 2.1 on Monday and we have to switch too. Unfortunately our playbooks don't work out-of-to box so reverting to older openshift-ansible is quickest workaround ATM, putting following lines into your env file should work:
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  openshift_ansible_git_rev: 08791978fdf3ee385760761d4fc6bc47febf1732

**Comment by snecklifter** [comment]
@jprovaznik thanks, we have also run into this issue and are testing this now.

**Comment by snecklifter** [comment]
@jprovaznik works for us, thanks.

**Comment by snecklifter** [comment]
@jprovaznik I may have spoke too soon, we are now running into https://github.com/openshift/openshift-ansible/issues/1865 when we use the above revision.
