### ISSUE TITLE
os-collect-config fails due to incorrect collectors parameter

### ISSUE THREAD

**Issue by snecklifter** [redhat-openstack/openshift-on-openstack#182]
We are deploying with RDO Mitaka and os-collect-config fails to start:

Jul 22 08:57:27 localhost os-collect-config: 2016-07-22 08:57:27.353 9807 CRITICAL os-collect-config [-] InvalidArguments: Unknown collectors ['["cfn"]', '["local"]', '["ec2"]']. Valid collectors are: ['heat_local', 'ec2', 'cfn', 'heat', 'request', 'local', 'zaqar']
Jul 22 08:57:27 localhost os-collect-config: 2016-07-22 08:57:27.353 9807 TRACE os-collect-config Traceback (most recent call last):
Jul 22 08:57:27 localhost os-collect-config: 2016-07-22 08:57:27.353 9807 TRACE os-collect-config   File "/usr/bin/os-collect-config", line 10, in <module>
Jul 22 08:57:27 localhost os-collect-config: 2016-07-22 08:57:27.353 9807 TRACE os-collect-config     sys.exit(**main**())
Jul 22 08:57:27 localhost os-collect-config: 2016-07-22 08:57:27.353 9807 TRACE os-collect-config   File "/usr/lib/python2.7/site-packages/os_collect_config/collect.py", line 245, in **main**

In /etc/os-collect-config.conf we see:

[DEFAULT]
command = os-refresh-config
collectors = ["ec2", "cfn", "local"]
collectors = ["ec2", "cfn", "local"]
collectors = ["ec2", "cfn", "local"]

**Comment by jprovaznik** [comment]
Hello,
I guess it's related to this change: https://review.openstack.org/#/c/289097/
Could you try change:
https://github.com/redhat-openstack/openshift-on-openstack/blob/master/collect-config-setup/fragments/configure_config_agent.sh#L35
to:
collectors = {{.}}

same as here:
https://github.com/openstack/heat-templates/blob/master/hot/software-config/heat-container-agent/scripts/configure_container_agent.sh#L45

Note that we did not tested these templates on Mitaka yet - only Liberty on centos/rhel are known to work.

**Comment by snecklifter** [comment]
@jprovaznik thanks for fast response.

Yes, this has worked for us. Have submitted PR.
