### ISSUE TITLE
Ansible run fails: an unexpected type error occurred.

### ISSUE THREAD

**Issue by snecklifter** [redhat-openstack/openshift-on-openstack#185]
We see the following error on RDO Mitaka when deploying OpenShift

TASK: [openshift_hosted | Retrieve list of openshift nodes matching router selector] **\* 
skipping: [darren1-origin-master-0.example.com]

TASK: [openshift_hosted | set_fact ] *****************************************\* 
<darren1-origin-master-0.example.com> ESTABLISH CONNECTION FOR USER: centos
fatal: [darren1-origin-master-0.example.com] => Failed to template {{ openshift.hosted.router.replicas | default((openshift_hosted_router_nodes_json.stdout | from_json)['items'] | length) }}: an unexpected type error occurred. Error was expected string or buffer

FATAL: all hosts have already failed -- aborting

**Comment by jprovaznik** [comment]
I'm looking at this one now. IIRC I've noticed this last week when deploying registry (-P deploy_registry), you should probably not hit it when omitting this param.

**Comment by snecklifter** [comment]
@jprovaznik thanks for looking at this. We are not deploying a registry so I'm not sure why we are seeing this. Please let us know if there is any additional information that would help.

**Comment by jprovaznik** [comment]
I couldn't reproduce this now, could you please paste your env file and parameters used for stack-create command?

**Comment by snecklifter** [comment]
@jprovaznik thanks, details here:

https://paste.fedoraproject.org/395240/43799514/
