### ISSUE TITLE
two OpenShift deployments on one OpenStack?

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#199]
Hi folks,

Have any of you tried a second deployment and heat stack alongside the first?  I'm having some trouble with neutron load balancing, and I'm wondering if any of this has been tried before.

Thanks!
-judd

**Comment by juddmaltin-dell** [comment]
My controllers were messed up.  Got them squared away.

Now, etcd data problems:

```
TASK: [etcd_certificates | Ensure generated_certs directory present] **********
fatal: [judd1-1471559092-openshift-master-0.10example.com] => Failed to template {{ etcd_needing_client_certs | default([]) }}: Failed to template {{ g_master_hosts | union(g_node_hosts) | union(g_etcd_hosts) | union(g_lb_hosts) | union(g_nfs_hosts) | union(g_new_node_hosts)| union(g_new_master_hosts) | default([]) }}: an unexpected type error occurred. Error was unsupported operand type(s) for +: 'set' and 'unicode'
```

Reconstructing this seems daunting to say the least.  SMH - Ansible?  Really?

Anyway, any ideas about what in etcd I might go edit to make this template actually work?

Thanks!
-judd

**Comment by jprovaznik** [comment]
Hi Judd,
yes - you can run multiple stacks alongside. The etcd_certificates - I bet you are deploying with flannel - this is currently broken:
in 3.2: https://github.com/openshift/openshift-ansible/issues/2326
in 3.3: https://github.com/openshift/openshift-ansible/issues/2322

I didn't find how to fix it yesterday. Openshift-sdn deployment should work though.

**Comment by juddmaltin-dell** [comment]
OpenShift-SDN deployments fail on my kit because (I think) we use VLANs, not vxVLANs.  I understand Red Hat uses vxVLANs, correct?

**Comment by juddmaltin-dell** [comment]
Do you know a good prior commit SHA that I could use?  I hadn't deployed in a while prior to this, and I'd be find to roll back to there.

**Comment by jprovaznik** [comment]
Yes - I use vxlan. Not sure about "known to work" commit ATM :( . When using openshift-ansible from github, it might be related to ca.crt -> ca-bundle.crt rename (based on Jason's comment here #2326), When installing opsnhift-ansible from rpms, I'm testing now if downgrading the rpm helps or not.

**Comment by jprovaznik** [comment]
@juddmaltin-dell flannel deployment is passing again when using current openshift-ansible master branch (thanks to this PR https://github.com/openshift/openshift-ansible/pull/2359)

**Comment by juddmaltin-dell** [comment]
WOW!  Thanks @jprovaznik !
