### ISSUE TITLE
Deploy fails when deploy_registry is True

### ISSUE THREAD

**Issue by dkranz** [redhat-openstack/openshift-on-openstack#224]
The deployment with the attached  parameters file works, but fails if deploy_registry is true with the following error on the master node where origin-node.service failed to start:

[root@my-openshift-origin-master-0 ~]# systemctl -l status origin-node.service
● origin-node.service - Origin Node
   Loaded: loaded (/usr/lib/systemd/system/origin-node.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/origin-node.service.d
           └─openshift-sdn-ovs.conf
   Active: activating (start) since Fri 2016-09-09 10:45:42 EDT; 29s ago
     Docs: https://github.com/openshift/origin
 Main PID: 17259 (openshift)
   CGroup: /system.slice/origin-node.service
           └─17259 /usr/bin/openshift start node --config=/etc/origin/node/node-config.yaml --loglevel=2

Sep 09 10:46:08 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:08.259582   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:08 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:08.761275   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:09 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:09.263306   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:09 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:09.764918   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:10 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:10.259913   17259 openstack.go:257] Failed to find compute endpoint: No suitable endpoint could be found in the service catalog.
Sep 09 10:46:10 my-openshift-origin-master-0.example.com origin-node[17259]: E0909 10:46:10.259940   17259 kubelet.go:1131] Unable to construct api.Node object for kubelet: failed to get instances from cloud provider
Sep 09 10:46:10 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:10.266612   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:10 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:10.768464   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:11 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:11.270444   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...
Sep 09 10:46:11 my-openshift-origin-master-0.example.com origin-node[17259]: W0909 10:46:11.772205   17259 subnets.go:110] Could not find an allocated subnet for node: my-openshift-origin-master-0.example.com, Waiting...

**Comment by dkranz** [comment]
[parameters.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/464274/parameters.txt)

**Comment by dkranz** [comment]
[parameters.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/464287/parameters.txt)

**Comment by dkranz** [comment]
[parameters.txt](https://github.com/redhat-openstack/openshift-on-openstack/files/464297/parameters.txt)

**Comment by jprovaznik** [comment]
Hi David,
based on this error:
"Sep 09 10:46:10 my-openshift-origin-master-0.example.com origin-node[17259]: E0909 10:46:10.259940 17259 kubelet.go:1131] Unable to construct api.Node object for kubelet: failed to get instances from cloud provider"

Openshift probably has a problem to connect to your Openstack. Can you please double-check your Openstack parameters are correct and also try to check manually an openstack command from my-openshift-origin-master-0.example.com (e.g. "nova list") to check credentials work?

**Comment by jprovaznik** [comment]
the problem in this case was region mismatch - RegionOne was passed, but regionOne is used in "keystone catalog" output.
