### ISSUE TITLE
Nodes do not have floating ips

### ISSUE THREAD

**Issue by dkranz** [redhat-openstack/openshift-on-openstack#226]
The README says "Every VM in this configuration is also given a floating IP address on the public network. This provides direct access to the master and node hosts when needed." But this doesn't seem to be the case. The infra,lb,master hosts have fips but not the node.

| ID                                   | Name                                          | Status | Task State | Power State | Networks                                                                                                              |
+--------------------------------------+-----------------------------------------------+--------+------------+-------------+-----------------------------------------------------------------------------------------------------------------------+
| a9ebebbb-969b-4ab8-93ed-01de3140b0ef | my-openshift-infra.example.com                | ACTIVE | -          | Running     | my-openshift-fixed_network-zbl65d323mym=192.168.0.5, 10.8.173.126                                                     |
| 15991244-9e99-4fe4-bc83-89f667c787f0 | my-openshift-lb                               | ACTIVE | -          | Running     | my-openshift-fixed_network-zbl65d323mym=192.168.0.7, 10.8.173.125                                                     |
| a656f093-5283-4db6-9904-e1eb03b018f5 | my-openshift-origin-master-0.example.com      | ACTIVE | -          | Running     | my-openshift-fixed_network-zbl65d323mym=192.168.0.6, 10.8.173.131; my-openshift-cluster_network-tvhcfmzjcedl=10.0.0.4 |
| 7c8a4654-867f-4116-8fb4-53bef434354a | my-openshift-origin-node-w3s10t9y.example.com | ACTIVE | -          | Running     | my-openshift-fixed_network-zbl65d323mym=192.168.0.8; my-openshift-cluster_network-tvhcfmzjcedl=10.0.0.5               |

**Comment by juddmaltin-dell** [comment]
That's by design.  The README should be updated.
