### ISSUE TITLE
Deploy on Mitaka fails

### ISSUE THREAD

**Issue by CuB0** [redhat-openstack/openshift-on-openstack#229]
Hi to everyone.

I'm trying to deploy openshift-on-openstack following the docs provided with this repo.

After calling: heat stack-create my-openshift -t 180 \
  -e openshift_parameters.yaml \
  -f openshift-on-openstack/openshift.yaml

I receive the following error:

ERROR: Failed to validate: : resources.loadbalancer: : HEAT-E99001 Service neutron is not available for resource type OS::Neutron::Pool, reason: Service endpoint not in service catalog.

My openstack setup uses neutron-lbaasv2-agent version 8.1.2

I'm doing something wrong or by now there's some king of problem deploying on Mitaka?

Thanks in advance.

Davide

**Comment by jprovaznik** [comment]
Hi Davide,
LBaaSv2 is currently not supported in openshift-on-openstack templates (I think LBaaSv2 support was added into Heat recently - in Mitaka) which was released for RHEL OSP just few weeks ago. We will for sure add support for LBaaSv2 in future, but meantime you have to use either v1 (openstack-neutron-lbaas-8.0.0-1.el7ost.noarch) or some other loadbalancer type (dedicated or external - https://github.com/redhat-openstack/openshift-on-openstack#select-loadbalancer-type)

**Comment by CuB0** [comment]
Thank you very much for the clear answer.

All the best.

Davide
