### ISSUE TITLE
Milestone request?

### ISSUE THREAD

**Issue by juddmaltin-dell** [redhat-openstack/openshift-on-openstack#230]
Hi!

If I'm happy with the project right now, and I'd like to point my users to it in paper (or PDF) documentation, would it best to request a release or tag?  What's the process for requesting a tag or version bump? I'd rather not document a commit SHA. A PR would would, but seems a bit contextually arbitrary.

Thanks very much,
-judd

**Comment by jprovaznik** [comment]
Good point - time for tagging current state. Though both #213 and #225 PRs fix some issues which can be hit be user, so I would prefer to merge them before tagging. A PR which bumps version in rpm spec is needed anyway, followed up by building an RPM. This is usually driven by @lebauce (Sylvain, what do you think about new release, would you have time to merge the linked PRs and make a build?)

**Comment by lebauce** [comment]
@jprovaznik I think it is a good time to do a release. I merged both PRs.
I'll bump the RPM version, create the tag and make a build

**Comment by jprovaznik** [comment]
@lebauce cool, thanks!

**Comment by jprovaznik** [comment]
There is a new tag 0.8.0 (https://github.com/redhat-openstack/openshift-on-openstack/tree/v0.8.0), thanks @lebauce

**Comment by juddmaltin-dell** [comment]
Thanks, guys!

**Comment by juddmaltin-dell** [comment]
Wait a second - doesn't this leave us vulnerable to openshift-ansible master moving away from us?  Shouldn't we pin that to a tag, too?
