### ISSUE TITLE
Invalid URL scheme

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#235]
Hi everybody, when I execute this command:

```
heat stack-create my-openshift -t 180  -e openshift_parameters.yaml  -f openshift-on-openstack/openshift.yaml
```

I get this output:

```
ERROR: Could not fetch remote template "openshift-on-openstack/registry_ephemeral.yaml": Invalid URL scheme
```

BUT when I vim "openshift-on-openstack/registry_ephemeral.yaml", the file is opened!!!

what is the problem? 
thanks for your help....

**Comment by mahsa-frj** [comment]
doesn't anybody know?

**Comment by jprovaznik** [comment]
Hi, I think this is caused by heatclient <-> heat-engine version incompatibility in Centos 7. I've updated this upstream bug: https://bugs.launchpad.net/python-heatclient/+bug/1534423/comments/7

The fix would probably be using newer heatclient version (and make sure it's available in centos).

**Comment by mahsa-frj** [comment]
thanks @jprovaznik , yes, it's about heatclient version. I used the  openstack liberty, and creation of heat was successful.

**Comment by mahsa-frj** [comment]
@jprovaznik  Hi.
in that url:  https://bugs.launchpad.net/python-heatclient/+bug/1534423/comments/7, you say, this instruction works on heatclient 1.2. how do you install openstack that your heat version is 1.2?
in liberty, the version of heat is 0.8. but after the creation of heat, I have some problem.

**Comment by jprovaznik** [comment]
@mahsa-frj on the CentOS deployment where I hit this issue I used heatclient-1.2 from RHEL, another alternative is installing with "pip install"

**Comment by mahsa-frj** [comment]
thanks @jprovaznik . my heatclient was updated successfully.
