### ISSUE TITLE
RFE: Allow selection of instance flavors for different VM classes.

### ISSUE THREAD

**Issue by markllama** [redhat-openstack/openshift-on-openstack#252]
I'd like to be able to specify not just the VM image but also the flavor for each type of host.

_openshift_parameters.yaml:_

```
flavor: m1.medium  # default flavor - used for VMs when no flavor is specified

bastion_image: rhel72
bastion_flavor: m1.small

master_image: rhel72
master_flavor: m1.medium

infra_image: rhel72
infra_flavor: m1.large

node_image: rhel72
node_flavor: m1.medium
```

**Comment by lebauce** [comment]
https://github.com/lebauce/openshift-on-openstack/tree/multi-flavors

**Comment by markllama** [comment]
Merged: closing.  Thank you.
https://github.com/redhat-openstack/openshift-on-openstack/pull/255
