### ISSUE TITLE
Allow "subdomain" for apps to be provided as a parameter to the heat stack

### ISSUE THREAD

**Issue by markllama** [redhat-openstack/openshift-on-openstack#258]
Currently the app wildcard subdomain is composed:

```
*.cloudapps.<domain_name>
```

It would be helpful if it were possible to specify the "subdomain" portion of the app record.

```
app_subdomain: "apps"
```

would yield

```
*.apps.<domain_name>
```

**Comment by markllama** [comment]
perhaps this would be called `router_lb_subdomain` or some such.  I'm not sure how best to name it so that users will understand the effect.

**Comment by ganhuang** [comment]
"subdomain" is really need for exposed routes, and this variable should _not_ related to "domain_name" which is set in heat template.  The users should be able to specify what they need in inventory hosts. So I suggest to specify it by "extra_openshift_ansible_params", and leave a default subdomain if users don't specify it explicitly.

https://github.com/openshift/openshift-ansible/blob/master/inventory/byo/hosts.ose.example#L229
