### ISSUE TITLE
node IP address flip-flopping

### ISSUE THREAD

**Issue by vbartoni** [redhat-openstack/openshift-on-openstack#308]
Hi,
At our deployment nodes seem to change HOST IP every minute or so, which causes external  requests to service to block. The request is unblocked and returns after flip-flopping again to correct IP address.
Maybe someone would have a hint what to look at.

Good situation, when request works fine (ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com adresses from eth0: 192.168.10.7)

> ocp-pk2-infra-0.teco.demo.tieto.com                ocp-pk2-infra-0.teco.demo.tieto.com                192.168.10.6   10.1.3.0/24
> ocp-pk2-oshift-master-0.teco.demo.tieto.com        ocp-pk2-oshift-master-0.teco.demo.tieto.com        192.168.10.4   10.1.1.0/24
> ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com   ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com   192.168.10.7   10.1.2.0/24
> ocp-pk2-oshift-node-o97m90ur.teco.demo.tieto.com   ocp-pk2-oshift-node-o97m90ur.teco.demo.tieto.com   192.168.10.8   10.1.0.0/24

Named DNS server at bastion works nicely, and for host names above returns also IP addresses from above.

Bad situation, when request is blocked because IP address of ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com changed to one at eth1 (10.10.0.4 )

> [root@ocp-pk2-oshift-master-0 ~]# oc get hostsubnet
NAME                                               HOST                                               HOST IP        SUBNET
ocp-pk2-infra-0.teco.demo.tieto.com                ocp-pk2-infra-0.teco.demo.tieto.com                192.168.10.6   10.1.3.0/24
ocp-pk2-oshift-master-0.teco.demo.tieto.com        ocp-pk2-oshift-master-0.teco.demo.tieto.com        192.168.10.4   10.1.1.0/24
ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com   ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com   10.10.0.4      10.1.2.0/24
ocp-pk2-oshift-node-o97m90ur.teco.demo.tieto.com   ocp-pk2-oshift-node-o97m90ur.teco.demo.tieto.com   192.168.10.8   10.1.0.0/24

Wandering what is causing the flip-flop, and where from is the faulty IP address coming - it's not from DNS for sure.
Maybe from openshift somehow, since node appear to have two IP addresses, and the other one is returned each time?

> [root@ocp-pk2-oshift-master-0 ~]# oc describe node ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com
Name:                   ocp-pk2-oshift-node-69xf7vp4.teco.demo.tieto.com
.
.
Addresses:              192.168.10.7,10.10.0.4

**Comment by detiber** [comment]
With cloud provider integration enabled the IP addresses for the node come from a lookup via the openstack api. I'm not sure if there is a way to prevent use of the non-routable one.

**Comment by vbartoni** [comment]
Thanks detiber.
This appears to be in issue in Openshift code, and not a configuration problem.
It seems there might be a problem with the resolver order being random.
Openshift people are working on the fix at the moment.
