### ISSUE TITLE
Issue while installation

### ISSUE THREAD

**Issue by 201sandeep** [redhat-openstack/openshift-on-openstack#309]
Hello, 

i am trying to install openshift using the same method described here but getting below error, Can someone please help me ?

[root@redcontroller ~(keystone_admin)]# heat stack-create my-openshift -t 180   -e openshift_parameters.yaml   -f openshift-on-openstack/openshift.yaml
ERROR: The Referenced Attribute (bastion_host resource.host) is incorrect.
[root@redcontroller ~(keystone_admin)]#

Tx

**Comment by jprovaznik** [comment]
hi, could you please provide more details?
heat resource-list -n2 stack
heat event-list -n2 stack
nova list

**Comment by dougsaus** [comment]
Was this issue resolved for you?  I am receiving the same thing just running the basic examples from the README.  This is the only reference I could find to someone having the exact same issue.

**Comment by ioggstream** [comment]
@Delmonte3161 no event-list, no party.

@markllama this could be closed, as it may refer to an older version of templates.

**Comment by ioggstream** [comment]
@201sandeep if it's ok, can you please close this ticket?

**Comment by 201sandeep** [comment]
Sorry for no response, Thanks that u have closed
