### ISSUE TITLE
Failed Install 

### ISSUE THREAD

**Issue by this-tech** [redhat-openstack/openshift-on-openstack#31]
Will not deploy master nodes 
yum -y install openshift-ansible-roles openshift-ansible-playbooks
not found

**Comment by this-tech** [comment]
Provided github url for OSO, same results

**Comment by this-tech** [comment]
Workaround is to update defaults in openshift.yaml. They could also be provided as env variables 

openshift_ansible_git_url:
    type: string
    description: >
      The URL to the git repository with the openshift-ansible templates to
      clone.
    default: "https://github.com/openshift/openshift-ansible.git"

  openshift_ansible_git_rev:
    type: string
    description: >
      The git revision of the openshift-ansible repository to check out to.
    default: "prod"

**Comment by jprovaznik** [comment]
Fixed by PR #33
