### ISSUE TITLE
os_collect_config.cfn [-] 403 Client Error: AccessDenied

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#317]
Hi everybody, in bastion node when the cloud-init finished I get the below error in /var/log/messages:

    Feb  8 12:34:52 openshift-dep-3-bastion os-collect-config: 2017-02-08 12:34:52.903 19225 WARNING os-collect-config [-] Source [cfn] Unavailable.
    Feb  8 12:34:52 openshift-dep-3-bastion os-collect-config: 2017-02-08 12:34:52.903 19225 WARNING os_collect_config.local [-] /var/lib/os-collect-config/local-data not found. Skipping
    Feb  8 12:34:52 openshift-dep-3-bastion os-collect-config: 2017-02-08 12:34:52.903 19225 WARNING os_collect_config.local [-] No local metadata found (['/var/lib/os-collect-config/local-data'])
    Feb  8 12:35:26 openshift-dep-3-bastion os-collect-config: 2017-02-08 12:35:26.090 19225 WARNING os_collect_config.cfn [-] 403 Client Error: AccessDenied

please help me to understand what is my problem?
thanks in advanced

**Comment by xaviou** [comment]
Hello @mahsa-frj, I have the same warning messages. How did you solve it?
