### ISSUE TITLE
Wait Handle: Authorization Failed

### ISSUE THREAD

**Issue by TimoL** [redhat-openstack/openshift-on-openstack#382]
Hi everyone,

I'm struggling to setup OpenShift on OpenStack. I did not find any relevant other issue - Sorry if I just used the wrong search terms.

My Issue: During the heat deployment, an error is raised during creation of hosts (I assume bastion is the first host to be created).

```
heat event for resource "bastion_host":
AuthorizationFailure: resources.bastion_host.resources.wait_handle: Authorization failed.
```

What do I do wrong?

Any help or hints is greatly appreciated.

BR, Timo

**Comment by ioggstream** [comment]
@TimoL 
- which openstack version?
- do you have a suitable token timeout?

**Comment by TimoL** [comment]
@ioggstream 
* OpenStack Newton Release
* token timeout should be default (according to the admin)

It also doesn't look like a timeout issue, since it always happens at exactly the same step during the deployment.

**Comment by greeninja** [comment]
@TimoL - ran in to this as well, heat_stack_owner was not configured with the correct role and the role for the project didn't exist. 
We checked back through the heat install: https://docs.openstack.org/heat/pike/install/ to make sure everything existed.

**Comment by ioggstream** [comment]
@TimoL ensure that the configuration is synced between all controllers too.

**Comment by TimoL** [comment]
@greeninja and @ioggstream: Thanks for your help, I'll check with our OpenStack admins.

**Comment by TimoL** [comment]
short update:

due to overlapping vacations we did not make any progress.
We're about to start testing again.

**Comment by ioggstream** [comment]
Hint: create a new stack with a single node and a wait handle and try to debug that checking controllers logs.

Are you using the curl_cli attribute to get the address to call?

**Comment by TimoL** [comment]
Hi @ioggstream,

that's a good idea, I'll try to create a minimal heat template replicating the the issue.
This way our admin can reproduce the issue far better (we're not in the same country...)

**Comment by TimoL** [comment]
closing old issue
