### ISSUE TITLE
heat signaling?

### ISSUE THREAD

**Issue by broskos** [redhat-openstack/openshift-on-openstack#49]
I seem to be having trouble with resources not signaling complete.  Using the HA setup, the lb completes, and the infra_host builds.  Looking in cloud-init logs I see everything completed successfully:
- notify_success 'OpenShift node has been prepared for running ansible.'
  Feb 25 08:12:55 localhost cloud-init: + curl -i -X POST -H 'X-Auth-Token: df69949e37644d94a9a8345ae72b697b' -H 'Content-Type: application/json' -H 'Accept: application/json' http://10.12.32.10:8004/v1/be5e2313437b44f18c09889f571ae15d/stacks/my_openshift-infra_host-r6ypfk4jlz5p/ed63786b-8812-4f99-bcf5-071989ac7431/resources/wait_handle/signal --data-binary '{"status": "SUCCESS", "reason": "OpenShift node has been prepared for running ansible.", "data": "OpenShift node has been prepared for running ansible."}'

However the stack does not seem to advance, instead it stays 'create_in_progress'
deployment_tune_ansible   | 5363098c-fa5b-4807-938d-55fafaf47c24                                                | OS::Heat::SoftwareDeployment                                                                  | CREATE_IN_PROGRESS | 2016-02-25T13:06:51Z | infra_host      |

If I use heat resource-signal and manually signal that task as complete, it moves on to deploying the 3 masters, but they get stuck the same way after the work from cloud-init is done.

Any ideas on what is going on here?

**Comment by jprovaznik** [comment]
deployment_tune_ansible is a SoftwareDeployment resource which is triggered by os-collect-config service (heat agent running inside VM), these sw deployments run in post cloud-init phase. If it's stuck in IN_PROGRESS state, I can think of 2 reasons:
1) cloud-init on infra host didn't finish yet for some reason - it's not this case though based on the successful notify_success above
2) os-collect-config on the infra node has issues running the deployment_tune_ansible script. Could you please check "journalctl -u os-collect-config" on the infra node - there should be a reason. Based on the fact that the heat stack is stuck in IN_PROGRESS state for a while, my guess would be that os-collect-config is failing to fetch instance metadata from heat-api-cfn server -> is heat-api-cfn up and running in your openstack deployment?

**Comment by broskos** [comment]
Jan - Thank you very much.  I'm missing heat-api-cfn server.  I'll get that
turned up and should be fine.

Brent Roskos
Senior Cloud Architect
Cloud Practice
Red Hat Consulting
678-744-3623

**Comment by jprovaznik** [comment]
Cool. We should improve our documentation to clarify openstack requriements as you are not the first one hitting this issue. I opened https://github.com/redhat-openstack/openshift-on-openstack/issues/50 to make sure we don't forget.

**Comment by haklein** [comment]
you also need to make sure the the heat metadata service is reachable from the nova node. You can adjust the listen ip in the heat.conf on the controller
