### ISSUE TITLE
Add openstack service requirements into README

### ISSUE THREAD

**Issue by jprovaznik** [redhat-openstack/openshift-on-openstack#50]
We need to improve our documentation with information what openstack services are used by these templates - missing heat-api-cfn is the most common trap for anyone trying this out.

**Comment by sferich888** [comment]
Shoulden't the packstack (from the example cover this)?

**Comment by jprovaznik** [comment]
The packstack deployment example is not sufficient - not everybody uses packstack and others use an already existing openstack environment.
