### ISSUE TITLE
Architecture diagram needs to add OpenShift "router" (http+ reverse proxy)

### ISSUE THREAD

**Issue by markllama** [redhat-openstack/openshift-on-openstack#51]
Inbound connections to OpenShift apps must pass through an haproxy reverse proxy known as the "OpenShift Router".  This process accepts all inbound IP requests for the OpenShift apps and forwards them to the correct node using the Server: HTTP header and a map maintained by the OpenShift master.

The proxy IP address is the target of the DNS A Record for the application DNS "wildcard" domain.

The architecture diagram should include the OpenShift router and the architecture write-up should make reference to it and explain it.

**Comment by lebauce** [comment]
Fixed by https://github.com/redhat-openstack/openshift-on-openstack/pull/114
