### ISSUE TITLE
heat stack-create failing: resources.lb_monitor: 404 Not Found  The resource could not be found

### ISSUE THREAD

**Issue by rawlingsj** [redhat-openstack/openshift-on-openstack#61]
After previously successfully creating an OpenShift cluster using this awesome heat template I've tried again with the latest master and run into the error below.  It's been about 4 weeks since I ran the script that worked for me, after renaming env.yaml > openshift_parameters.yaml, removing `dns_hostname` renaming `master_hostname_prefix` and `node_hostname_prefix` with `master_hostname` and `node_hostname` respectfully I hoped it would just work but I get this error during `heat stack-create my_openshift3 -t 260 -e openshift_parameters.yaml -f openshift-on-openstack/openshift.yaml`..

```
| stack_status_reason   | Resource CREATE failed: NeutronClientException:                                                                                                                                                        |
|                       | resources.lb_monitor: 404 Not Found  The resource could                                                                                                                                                |
|                       | not be found.
```

I'm no openstack expert so apologies if this is not the heat script fault but any pointers would be appreciated. All neutron services apart from a cleanup seem to be running ok..

```
systemctl | grep neut
neutron-dhcp-agent.service                                                                       loaded active running   OpenStack Neutron DHCP Agent
neutron-l3-agent.service                                                                         loaded active running   OpenStack Neutron Layer 3 Agent
neutron-metadata-agent.service                                                                   loaded active running   OpenStack Neutron Metadata Agent
neutron-openvswitch-agent.service                                                                loaded active running   OpenStack Neutron Open vSwitch Agent
neutron-ovs-cleanup.service                                                                      loaded active exited    OpenStack Neutron Open vSwitch Cleanup Utility
neutron-server.service                                                                           loaded active running   OpenStack Neutron Server
```

**Comment by lebauce** [comment]
Hi. The templates now make use of the Neutron LBaaS feature and your setup does not seem to have it enabled.

As it's probably the case for many Openstack deployments, we are in the process of adding back the code that use dedicated nodes for load balancing - therefore not requiring the Neutron LbaaS feature : https://github.com/redhat-openstack/openshift-on-openstack/pull/59

Once this is merged, your stack should be created successfully.

**Comment by rawlingsj** [comment]
sounds great - many thanks for the update

**Comment by lebauce** [comment]
@rawlingsj The PR has been merged, it should fix your problem.

**Comment by jprovaznik** [comment]
Yep, you can now use "-e env_loadbalancer_dedicated.yaml" if LBaaS is not available, closing this.
