### ISSUE TITLE
deploy_registry fails: 

### ISSUE THREAD

**Issue by markllama** [redhat-openstack/openshift-on-openstack#66]
When attempting to deploy the OpenShift registry updating the IP tables fails, causing the stack create to fail:

https://github.com/redhat-openstack/openshift-on-openstack/blob/master/fragments/master-ansible.sh#L230

```
[cloud-user@oshift-infra ~]$ sudo iptables -I OS_FIREWALL_ALLOW -p tcp -m tcp --dport 1936 -j ACCEPT
iptables: No chain/target/match by that name.
```

**Comment by jprovaznik** [comment]
Fixed by https://github.com/redhat-openstack/openshift-on-openstack/commit/83d5522a61e898c51cbc3fc499c2dcf02f564ee1

**Comment by lebauce** [comment]
I'm a bit late on this one :-)
I don't understand why the iptables was set when `$deploy_registry == "True"` in the first place as it was related to the stats of the router.
