### ISSUE TITLE
Attempt to deploy OpenShift router causes stack-create to fail

### ISSUE THREAD

**Issue by markllama** [redhat-openstack/openshift-on-openstack#67]
When an OpenShift stack is created with the deploy_router switch set, the services deployment fails.

heat stack-create oshift -e openshift-on-openstack/env_origin.yaml -f openshift-on-openstack/openshift.yaml -P external_network=public -P flavor=m1.shift -P server_image=centos72 -P master_server_group_policies=affinity -P master_docker_volume_size_gb=6 -P node_docker_volume_size_gb=4 -P deploy_router=True

```
tail -f /var/log/ansible-services-16767.log 
TASK: [Evaluate oo_masters] *************************************************** 
fatal: [localhost] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/services.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1   


```

```
Mar 24 19:20:40 oshift-infra os-collect-config[9501]: + ansible-playbook --inventory /var/lib/ansible/inventory /var/lib/ansible/services.yml
Mar 24 19:20:40 oshift-infra os-collect-config[9501]: [2016-03-24 19:20:40,080] (heat-config) [ERROR] Error running /var/lib/heat-config/heat-config-script/8cbd5259-3e31-4c56-a14e-36d096caed00. [2]
```

https://github.com/redhat-openstack/openshift-on-openstack/blob/master/fragments/master-ansible.sh#L234-L248

**Comment by lebauce** [comment]
Fixed by https://github.com/redhat-openstack/openshift-on-openstack/pull/85
