### ISSUE TITLE
Resource Details: infra_host

### ISSUE THREAD

**Issue by mahsa-frj** [redhat-openstack/openshift-on-openstack#83]
Hi, I'm using your instruction, and in this step 

```
heat stack-create my_openshift \
-e openshift_parameters.yaml \
-P master_count=1 \
-f openshift-on-openstack/openshift.yaml\
-e openshift-on-openstack/env_loadbalancer_none.yaml
```

the output in the command terminal was "CREATE_IN_PROGRESS" but in my openstack environment, in the stack -> resource section, in the infra_host resource type, i get this error:

Create Failed: ResourceInError: resources.infra_host.resources.docker_volume: Went to status error due to "Unknown" 

can we help me to understand, what is my problem?
thanks for your reply.

**Comment by jprovaznik** [comment]
Hi, docker_volume is a volume created in cinder, could you please check "cinder list/show" and /var/log/cinder/volume.log if there are more details about the error?

**Comment by mahsa-frj** [comment]
the output of volume.log:

```
2016-04-13 15:36:50.895 2634 WARNING cinder.openstack.common.loopingcall   [req-401a68e4-8647-4c08-b492-4a03577b2bd6 - - - - -] task u'<bound method Service.report_state  of <cinder.service.Service object at 0x2350090>>' run outlasted interval by 6.13 sec
```

and the cinder list output is:
    status = ERROR    and Bootable = false

**Comment by jprovaznik** [comment]
What is "cinder show xxx" output? If there is nothing in volume log you might need to check other logs in /var/log/cinder dir. 

Only guessing, but one of typical issues is that cinder backend volume is not big enough - e.g. packstack by default deploys only 20G cinder volume (and by default we allocate 25G volume per each node), if this is the case you can either increase your cinder capacity or use smaller volumes (*_docker_volume_size_gb params when creating the stack).

**Comment by mahsa-frj** [comment]
thanks @jprovaznik , I think my space is not enough, I'll try it again...

**Comment by jprovaznik** [comment]
Closing this as it was hopefully resolved based on last comment.
