### ISSUE TITLE
Stack create fails with deploy_router=true

### ISSUE THREAD

**Issue by jprovaznik** [redhat-openstack/openshift-on-openstack#84]
Due to this openshift-ansible commit https://github.com/openshift/openshift-ansible/commit/4ac07696f3db92d1361290c3a0d7b7637d3d1994 openshift_router role (which we use when deploying router) has been moved under a different role and ansible playbook fails.

**Comment by lebauce** [comment]
Fixed by https://github.com/redhat-openstack/openshift-on-openstack/pull/85

**Comment by jprovaznik** [comment]
This is actually not related to https://github.com/redhat-openstack/openshift-on-openstack/pull/85 . In this case the problem is that openshift_router role has been removed from openshift-ansible (replaced with secure_router).

**Comment by jprovaznik** [comment]
Openshift-ansible deployes router by default anyway, so I think we can remove this explicit playbook from our code. Same for registry, but there is a problem that openshift-ansible currently supports only nfs backend.

**Comment by jprovaznik** [comment]
Fixed in openshift-ansible
