### ISSUE TITLE
heat create fails when trying to install EPEL repo on infra node

### ISSUE THREAD

**Issue by rawlingsj** [redhat-openstack/openshift-on-openstack#89]
```
| stack_status_reason   | Resource CREATE failed: WaitConditionFailure:                                                                                                                                                          |
|                       | resources.infra_host.resources.wait_condition: could                                                                                                                                                   |
|                       | not install EPEL release 7-5
```

Sure enough I'm getting a 404 on the URL that's used..
`wget http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm`

I tried hacking https://github.com/redhat-openstack/openshift-on-openstack/blob/master/fragments/infra-boot.sh#L178 to  `yum -y install epel-release` which did install the 7-5 rpm but then the scripts failed further down the line..

```
| stack_status_reason   | Resource CREATE failed: WaitConditionFailure:                                                                                                                                                          |
|                       | resources.infra_host.resources.wait_condition: could                                                                                                                                                   |
|                       | not install openshift-ansible
```

So I guess they're two different versions and the latter doesn't have the `atomic-openshift-utils` which includes `openshift-ansible`.  

There's a fair amount of guess work that I've just done so probably got a fair few things wrong but thought the info might help.  Either way is there a work around that I can try as I'm unable to recreate my cluster that I just trashed?

**Comment by lebauce** [comment]
The EPEL issue was fixed by https://github.com/redhat-openstack/openshift-on-openstack/pull/88

**Comment by lebauce** [comment]
Regarding the openshift-ansible issue, you can try to pass the 2 following parameters to your stack :

```
  openshift_ansible_git_url: https://github.com/openshift/openshift-ansible.git
  openshift_ansible_git_rev: master
```

It will use openshift-ansible git repository instead of the RPM packages

**Comment by rawlingsj** [comment]
It certainly got a lot further in the script so this issue is fixed, it still failed but thats a separate problem, most likely mine as its run out of free floating ips.

Thanks!
