### ISSUE TITLE
Support for 3.1

### ISSUE THREAD

**Issue by chmouel** [redhat-openstack/openshift-on-openstack#9]
It seems that only 3.0 is supported currently it would be nice if we have support for 3.1

**Comment by jprovaznik** [comment]
Hi chmouel, commit https://github.com/redhat-openstack/openshift-on-openstack/commit/f8112739e38bbf3c3c4c7549b69aabaee990ae71 switches from 3.0 to 3.1, let me know if you hit any issue.
